### ISSUE TITLE
Implement pallete selection

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/ProjectLiveModules2#32]
@jaybee84 Suggested letting users select their own pallete.

@jaybee84  Should this be available to the end users (funders), or is this something that should be selected in the admin app by people from the DCC such as yourself?

**Comment by andrewelamb** [comment]
[Here](https://sjmgarnier.github.io/viridisLite/reference/figures/viridis-scales.png) are the viridis palletes that could be added with little trouble.

**Comment by andrewelamb** [comment]
@milen-sage @ychae Let's add this to the next sprint.

**Comment by jaybee84** [comment]
> Should this be available to the end users (funders), or is this something that should be selected in the admin app by people from the DCC such as yourself?

This request was made by one of our funders, so this high level control should be available to the funders/user

In light of Ashley's comment in today's meeting where funders/consortia may want to see their branding colors reflected in this tracker, the admin app should potentially have finer control on palletes and plot types

**Comment by andrewelamb** [comment]
I think the branding colors will be reflected in all the non plot objects (boxes, sidebars headers etc...) leaving the colors in the plots available to the user to play with, so that shouldn't be a problem.

**Comment by andrewelamb** [comment]
Here is what this will look like:
![PL2_palette](https://user-images.githubusercontent.com/7220713/176259192-27570ddd-4002-4f5d-9cf2-9e78970d5b63.jpg)
